### ISSUE TITLE
No scroll bar in setting menu for certain tabs

### ISSUE THREAD

**Issue by konatachan** [RoliSoft/RS-TV-Show-Tracker#2] opened 2014-02-15 22:00 UTC
Windows 7 x64, standart aero theme, problem persists in stable and nightly releases, 
In the settings tabs: General,Listing

**Comment by RoliSoft** [comment] 2015-11-28 18:53
Although I couldn't reproduce, a similar graphical bug regarding inconsistent sizing was fixed by commit 54ce20e3b7299038874cf698bfb25ef2bfab9ed6.

**Closed by RoliSoft** 2015-11-28 18:53 UTC
